### ISSUE TITLE
occur error

### ISSUE THREAD

**Issue by HadXu** [matsui528/nanosearch#1]
hello,I follow this repo,but occure error as follow,and my OS windows:

            raise ValueError(err_msg)

     

        elif isinstance(obj, Tensor) and allow_tensor:

          # Actually obj is just the object it's referring to.

          if obj.graph is not self:

            raise ValueError("Tensor %s is not an element of this graph." % obj)

          return obj

        elif isinstance(obj, Operation) and allow_operation:

          # Actually obj is just the object it's referring to.

          if obj.graph is not self:

            raise ValueError("Operation %s is not an element of this graph." % obj)

    ValueError: Tensor Tensor("fc1/Relu:0", shape=(?, 4096), dtype=float32) is not an element of this graph.

**Comment by matsui528** [comment]
Hi,
I cannot reproduce your results, but this post might help. https://github.com/fchollet/keras/issues/2397

**Comment by HadXu** [comment]
Thank you very much. This problem is solved as your suggestion.

**Comment by fcagroupj** [comment]
In keras, after loading model, call
    graph = tf.get_default_graph()
set this as global.
When predicting with the model, use 
    global graph
    with graph.as_default():
        (... do inference here ...)
