### ISSUE TITLE
May I know which Nearest Neighbor Algo is Used.

### ISSUE THREAD

**Issue by khalid5454** [matsui528/nanosearch#14]
Hello @matsui528
Would you like to mention which algo is used for a recommendation like Nearest Neighbour?
 #For Feature Extraction you used VGG16 so which one algo for recommendation.

Thanks

**Comment by matsui528** [comment]
Simple nearest neighbor search
https://github.com/matsui528/sis/blob/master/server.py#L31

**Comment by khalid5454** [comment]
Thanks for your response.Appreciate
