### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by github4f** [matsui528/nanosearch#15]
It seems that your code does not work with Tensorflow 2 (AttributeError: module 'tensorflow' has no attribute 'get_default_graph'). I have downgraded it to 1.4, but I encoutered another error (ImportError: cannot import name 'tf_utils').... 
could you please let m know what version of TF did you use? tnx

**Comment by chien-le** [comment]
Try `pip install tensorflow==1.15.0rc3`

**Comment by matsui528** [comment]
I removed `graph` stuff and now it should work with tensorflow2. 

Note to self: This `graph` was added because of some problems on the keras side. I hope that now everything is updated to tf2 and works well without `graph`. ref: https://github.com/matsui528/sis/issues/6
