### ISSUE TITLE
Getting internal server error while running flask app on default route http://127.0.0.1:5000/

### ISSUE THREAD

**Issue by ovaixalee** [matsui528/nanosearch#16]
**application.py** 
`import os

from flask import Flask, render_template, request
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker

app = Flask(__name__)

engine = create_engine("postgresql://postgres:123@localhost:5432/lecture3")
db=scoped_session(sessionmaker(bind=engine))

@app.route("/")
def index():
	flights =  db.execute("SELECT * FROM flights").fetchall()
	return render_template("index.html", flights=flights)

@app.route("/book", methods=["POST"])
def book():
	"Book a flight."
	
	name = request.form.get()
	
if __name__ == 'main':
	app.run()
	`

**Comment by matsui528** [comment]
this is not related to this repo
