### ISSUE TITLE
using postgres CUBE data extension ?

### ISSUE THREAD

**Issue by batara666** [matsui528/nanosearch#24]
It is possible to use the CUBE data extension ? so we don't need to worry about scaling

**Comment by matsui528** [comment]
I don't know the CUBE format. Please try.

**Comment by batara666** [comment]
I open a stackoverflow [question](https://stackoverflow.com/questions/65055229/trying-to-fit-postgresql-max-cube-by-reducing-numpy-nd-array) about "Trying to fit postgresql max CUBE by reducing numpy nd array"

**Comment by batara666** [comment]
[help wanted]
