### ISSUE TITLE
Getting 0.0.0.0 refused to connect

### ISSUE THREAD

**Issue by TrungHieu-Le** [matsui528/nanosearch#26]
Hello, 
When running "server.py" I got:
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

I copied URL: http://0.0.0.0:5000/ to run on Chorme, I got
This site can’t be reached
0.0.0.0 refused to connect.

Could you please help me? Thank you!

**Comment by matsui528** [comment]
Follow the issue template.
