### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by joaocps** [matsui528/nanosearch#27]
Hi !
Do you have any idea what performance it would be if I used 5 million images? How long would it take to return similar images?
Can the feature extraction process be done with GPU?

Regards,
João

**Comment by matsui528** [comment]
I haven't tried the search with 5 million images. It will probably take tens of seconds, or more. For such a case, I'd recommend using ANN libraries such as [annoy](https://github.com/spotify/annoy) or [faiss](https://github.com/facebookresearch/faiss).

You can use the GPU for feature extraction, and it will be faster.
