### ISSUE TITLE
where is database?

### ISSUE THREAD

**Issue by ARCHANA161210** [matsui528/nanosearch#5]
Hi,
I set up the environment started server and can see html file on localhost:5000 . But where is database this query image search for?

**Comment by matsui528** [comment]
Hi @ARCHANA161210 
Prepare images (`*.jpg`) by yourself, and put them on `sis/static/img/`, then run `$ python offline.py`

**Comment by ARCHANA161210** [comment]
I put one sample image of cat.jpg in img folder and run the offline.py
file. Now i have cat.pkl file in features folder. But where is Result?

And for online search engine ,where does database go?

Thanks your code really helpful.

Archana

**Comment by matsui528** [comment]
What do you mean "Result"? You can put cat images like `cat1.jpg`, `cat2.jpg`, ..., , `cat100.jpg` on `sis/static/img`. They are images search for. By `offline.py`, their features are extracted and saved on `sis/static/feature`, i.e., `cat1.pkl`, `cat2.pkl`, ...

After you launch a server (`server.py`), you can send a query image (`query_cat_img.jpg`) to the server via your browser. The server returns the ranked list of similar images (`cat23.jpg`, `cat36.jpg`, `cat3.jpg`, ...). They are results (`cat23.jpg` is similar to `query_cat_img.jpg`)

**Comment by ARCHANA161210** [comment]
I got it..Thank you sooooo much.I really appreciate...

**Comment by SagarikaR** [comment]
You project has really helped me.But how how i diaplay only the relative images.your code is displaying all yhe images.i want to display images which are only related to the query image

**Comment by matsui528** [comment]
You can change the number of returned images here https://github.com/matsui528/sis/blob/master/server.py#L32

**Comment by SagarikaR** [comment]
Is this method texture based or shape based or colour based image retrieval

**Comment by Priyabpoojari** [comment]
Query image is not displaying in our project as screenshot follows
![error](https://user-images.githubusercontent.com/42670093/69896461-bce57380-1365-11ea-9b3c-9070bed6aa29.PNG)
please help us as soon as possible
