### ISSUE TITLE
Version details

### ISSUE THREAD

**Issue by kashyap32** [matsui528/nanosearch#7]
Hi , can you please tell me the version details of keras?

Because I am getting this error :- ValueError: operands could not be broadcast together with shapes (0,) (4096,)

**Comment by anshul12112** [comment]
sir can you please tell me how to resolve this is issue. please help sir

**Comment by anshul12112** [comment]
> Hi , can you please tell me the version details of keras?
> 
> Because I am getting this error :- ValueError: operands could not be broadcast together with shapes (0,) (4096,)

i am getting same error . please help me in resolving this issue
